Controllers/01_Hethong/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using Gemini.Controllers.Bussiness;
using Gemini.Models._01_Hethong;

namespace Gemini.Controllers._01_Hethong
{
    public class NavController : GeminiController
    {
        /// <summary>
        /// Polycy Memu
        /// </summary>
        /// <returns></returns>
        public ActionResult Amenu()
        {
            try
            {
                var route = RouteTable.Routes.GetRouteData(HttpContext);
                var currentPortal = "admin";
                if (route != null)
                {
                    currentPortal = route.GetRequiredString("Portal");
                    ViewData["Portal"] = route.GetRequiredString("Portal");
                    var user = GetSettingUser();
                    if (user != null)
                    {
                        ViewData["Username"] = user.Username;
                        ViewData["GuidUser"] = user.Guid.ToString().ToLower().Trim();
                    }
                }

                var models = new List<SMenuModel>();
                var id = (FormsIdentity)User.Identity;
                FormsAuthenticationTicket authTicket = id.Ticket;
                var roleControls = DataGemini.SUsers.Where(s => s.Username.ToUpper().Equals(authTicket.Name.ToUpper())).Select(x => new { x.GuidRole }).FirstOrDefault();
                if (roleControls != null && (roleControls.GuidRole) != null)
                {
                    models = (from frc in DataGemini.FRoleControlMenus
                              join er in DataGemini.SRoles on frc.GuidRole equals er.Guid
                              join em in DataGemini.SMenus on frc.GuidMenu equals em.Guid
                              where frc.GuidRole == roleControls.GuidRole && em.Type == "ADMIN"
                              select new SMenuModel()
                              {
                                  Guid = em.Guid,
                                  Name = em.Name,
                                  Active = em.Active,
                                  Note = em.Note,
                                  FriendUrl = em.FriendUrl,
                                  GuidLanguage = em.GuidLanguage,
                                  GuidParent = em.GuidParent,
                                  Icon = string.IsNullOrEmpty(em.Icon) ? "001_Help" : em.Icon,
                                  LinkUrl = em.LinkUrl,
                                  OrderMenu = em.OrderMenu,
                                  RouterUrl = em.RouterUrl,
                                  Type = em.Type,
                              }).OrderBy(s => s.OrderMenu).ToList();
                }
                return View(models);
            }
            catch
            {
                return Redirect("/Error/ErrorList");
            }

        }

        /// <summary>
        /// Policy Toolbar
        /// </summary>
        /// <returns></returns>
        public ActionResult AToolbar()
        {
            try
            {
                var models = GetAllMainControlInMenu();

                Session["MainControls"] = models.Select(x => x.EventClick).ToList();

                return View(models);
            }
            catch
            {
                return Redirect("/Error/ErrorList");
            }
        }

        /// <summary>
        /// Policy Item 
        /// </summary>
        /// <returns></returns>
        public ActionResult AToolbarItem()
        {
            try
            {
                var models = GetAllEditControlInMenu();

                Session["EditControls"] = models.Select(x => x.EventClick).ToList();

                return View(models);
            }
            catch
            {
                return Redirect("/Error/ErrorList");
            }
        }

        /// <summary>
        /// Policy Tool Bar Under
        /// </summary>
        /// <returns></returns>
        public ActionResult AToolbarc()
        {
            try
            {
                var models = GetAllTabControlInMenu();

                Session["TabControls"] = models.Select(x => x.EventClick).ToList();

                return View(models);
            }
            catch
            {
                return Redirect("/Error/ErrorList");
            }
        }
    }
}

Controllers/01_Hethong/ResourceController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Resources;
using System.Web.Mvc;
using Gemini.Controllers.Bussiness;
using Gemini.Models;
using Gemini.Models._01_Hethong;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SINNOVA.Core;

namespace Gemini.Controllers._01_Hethong
{

    public class ResourceController : GeminiController
    {
        public ResourceController()
        {
        }

        public ActionResult Index()
        {

            return RedirectToAction("List");
        }

        /// <summary>
        /// List view grid
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            GetSettingUser();
            return View();
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request, string tukhoa, string filename)
        {
            if (filename.IsNullOrEmpty())
            {
                filename = @"Resource.resx";
            }
            string filePath = AppDomain.CurrentDomain.BaseDirectory + @"Resources\" + filename;
            var resSet = new ResXResourceSet(filePath);
            IDictionaryEnumerator dict = resSet.GetEnumerator();
            var listResourceModel = new List<ResourceModel>();
            while (dict.MoveNext())
            {
                var key = (string)dict.Key;
                var resource = new ResourceModel { Key = key, Value = resSet.GetString(key) };
                listResourceModel.Add(resource);
            }

            var find = new FINDBASEModel { tukhoa = vString.GetValueTostring(tukhoa) };
            DataSourceResult result =
                listResourceModel.Where(s => s.Value.Contains(find.tukhoa))
                    .OrderBy(s => s.Key)
                    .ToDataSourceResult(request);
            return Json(result);
        }


        private static void AddOrUpdateResource(string key, string value, string filePath)
        {

            List<DictionaryEntry> resx;
            using (var reader = new ResXResourceReader(filePath))
            {
                resx = reader.Cast<DictionaryEntry>().ToList();
                var existingResource = resx.FirstOrDefault(r => r.Key.ToString() == key);
                {
                    var modifiedResx = new DictionaryEntry() { Key = existingResource.Key, Value = value };
                    resx.Remove(existingResource); // REMOVING RESOURCE!
                    resx.Add(modifiedResx); // AND THEN ADDING RESOURCE!
                }
            }
            using (var writer = new ResXResourceWriter(filePath))
            {
                resx.ForEach(r => writer.AddResource(r.Key.ToString(), r.Value.ToString()));
                writer.Generate();
            }
        }


        private static void DeleteResource(string key, string value, string filePath)
        {

            List<DictionaryEntry> resx;
            using (var reader = new ResXResourceReader(filePath))
            {
                resx = reader.Cast<DictionaryEntry>().ToList();
                var existingResource = resx.FirstOrDefault(r => r.Key.ToString() == key);
                {
                    var modifiedResx = new DictionaryEntry() { Key = existingResource.Key, Value = value };
                    resx.Remove(existingResource); // REMOVING RESOURCE!
                }
            }
            using (var writer = new ResXResourceWriter(filePath))
            {
                resx.ForEach(r => writer.AddResource(r.Key.ToString(), r.Value.ToString()));
                writer.Generate();
            }
        }
        public ActionResult Edit(string key, string filename)
        {
            try
            {
                if (filename.IsNullOrEmpty())
                {
                    filename = @"Resource.resx";
                }

                string filePath = AppDomain.CurrentDomain.BaseDirectory + @"Resources\" + filename;
                List<DictionaryEntry> resx;
                ResourceModel viewModel;
                using (var reader = new ResXResourceReader(filePath))
                {
                    resx = reader.Cast<DictionaryEntry>().ToList();
                    var existingResource = resx.FirstOrDefault(r => r.Key.ToString() == key);
                    {
                        viewModel = new ResourceModel() { Key = existingResource.Key.ToString(), Value = existingResource.Value.ToString(), FilePath = filePath };
                    }
                }
                return PartialView("Edit", viewModel);
            }
            catch (Exception)
            {
                return Redirect("/Error/ErrorList");
            }

        }


        public ActionResult Delete(string key, string filename)
        {
            try
            {
                if (filename.IsNullOrEmpty())
                {
                    filename = @"Resource.resx";
                }

                string filePath = AppDomain.CurrentDomain.BaseDirectory + @"Resources\" + filename;
                List<DictionaryEntry> resx;
                ResourceModel viewModel;
                using (var reader = new ResXResourceReader(filePath))
                {
                    resx = reader.Cast<DictionaryEntry>().ToList();
                    var existingResource = resx.FirstOrDefault(r => r.Key.ToString() == key);
                    {
                        viewModel = new ResourceModel() { Key = existingResource.Key.ToString(), Value = existingResource.Value.ToString(), FilePath = filePath };
                    }
                }

                DeleteResource(viewModel.Key, viewModel.Value, viewModel.FilePath);
                DataReturn.ActiveId = 0;
                DataReturn.StatusCode = Convert.ToInt16(HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }

            return Json(DataReturn, JsonRequestBehavior.AllowGet);
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update(ResourceModel viewModel)
        {
            try
            {
                AddOrUpdateResource(viewModel.Key, viewModel.Value, viewModel.FilePath);
                DataReturn.StatusCode = 200;
                DataReturn.ActiveId = 0;
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }
            return Json(DataReturn, JsonRequestBehavior.AllowGet);
        }





    }
}

Views/Resource/Edit.cshtml
@model Gemini.Models._01_Hethong.ResourceModel
@{ Layout = "~/Views/Shared/_FormList.cshtml"; }
@Html.Action("AToolbarItem", "Nav")

<div class="k-edit-form-container" style=" overflow-x: hidden;">
    <form method="post" id="frmEdit" class="form-horizontal" role="form">
        <div id="Tabs">
            <ul>
                <li class="k-state-active">@Html.Label(@Gemini.Resources.Resource.LBasic)</li>
            </ul>
            @*Cơ bản*@
            <div>
                <div style="height: 0; overflow: hidden">
                    @Html.HiddenFor(model => model.Key)
                    @Html.HiddenFor(model => model.FilePath)
                    <input type="hidden" id="hfLuuvathem" value="0" /><input type="hidden" id="hfExpand" value="0" />
                    <button type="submit" id="btnLuu" style="visibility: hidden"></button>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 col-md-2">
                        @Html.Label("Value")
                        <span class="k-icon k-i-note" id="k-invalid"></span>
                    </div>
                    <div class="col-sm-10 col-md-10">
                        @Html.TextBoxFor(model => model.Value, new { @class = "k-textbox" })
                        <div>@Html.ValidationMessageFor(model => model.Value)</div>
                    </div>
                </div>

            </div>

        </div>
    </form>
</div>

<script>

    //Form submit
    var validator = $("#frmEdit").kendoValidator().data("kendoValidator");
    $("form").submit(function (event) {
        if (validator.validate() == true) {
            kendo.ui.progress(parent.$("#WidgetConfigWindow"), true);
            var frm = $('#frmEdit');
            var httpPost = $.post('@Url.Action("Update", "Resource")', frm.serialize(), function (dataResponse) {
                kendo.ui.progress(parent.$("#WidgetConfigWindow"), false);
                if (dataResponse.StatusCode == 200) {
                    parent.voidRefresh();
                    parent.ActiveRow(dataResponse.ActiveId);
                    if (parseInt($("#hfLuuvathem").val()) == 0) {
                        closeWindowEdit();
                    } else {
                        parent.Create('0');
                    }
                } else {
                    Notification('@Gemini.Resources.Resource.EditUnsuccessful', dataResponse.StatusCode, dataResponse.MessagError, '@Gemini.Resources.Resource.ListStatusNotificationError', true);
                }
            }).fail(function (xhr, status, error) {
                kendo.ui.progress(parent.$("#WidgetConfigWindow"), false);
                Notification('@Gemini.Resources.Resource.ListUnsuccessful', '@Gemini.Resources.Resource.ListStatus404', error, '@Gemini.Resources.Resource.ListStatusNotificationError', true);
            });
        }
        event.preventDefault();
    });


    function closeWindowEdit() {
        var window = parent.$("#WidgetConfigWindow").data("kendoWindow");
        window.close();
    }

    function voidRefreshItem() {
        if (parseInt($("#IsUpdate").val()) == 0) {
            parent.Create('0');
        } else if (parseInt($("#IsUpdate").val()) == 1) {
            parent.Edit('1');
        }
    }
    ToolbarItem_Click();
    KendoTabStrip();
    //Enter text box
    PreventEventTextSubmit();
    //Phím tắt
    KeyboardNavigationEdit();
</script>

Views/Resource/List.cshtml
@model IEnumerable<Gemini.Models._01_Hethong.ResourceModel>
@{
    Layout = "~/Views/Shared/_FormList.cshtml";
    int gridPageSize = ViewBag.Pagesize;
}

@*Menu main*@
@Html.Action("AToolbar", "Nav")

@*Grid main*@
<div>
    @(Html.Kendo().Grid<Gemini.Models._01_Hethong.ResourceModel>()
      .Name("grid")
      .Columns(columns =>
      {
          columns.Bound(p => p.Key).Width(120);
          columns.Bound(p => p.Value).Width(125);

      })
       .ToolBar(toolbar =>
    {
        toolbar.Template(@<text>
            <div class="form-horizontal toolbar">
                <div class="row">
                    <div class="col-md-1">
                        <label class="control-label">@Html.Label(@Gemini.Resources.Resource.LKeywordsearch)</label>
                    </div>
                    <div class="col-md-3">
                        <input class="k-textbox" id="txtSearch" onchange="txtSearch_textChanged()" style="width: 100%" />
                    </div>
                    <div class="col-md-2">

                    </div>
                    <div class="col-md-3">
                        @(Html.Kendo().DropDownList()
                                .Name("CbMa_nhom")
                                .HtmlAttributes(new { @class = "k-dropdown" })
                                .HtmlAttributes(new { style = "width:100%;z-index:1;" })
                                .Filter(FilterType.Contains)
                                .DataTextField("TenTrangthai")
                                        .DataValueField("Ghichu")
                                                 .Value("Resource.resx")
                               .DataSource(source => source.Read(read => read.Action("Dm_trangthai", "Combo", new { nhomtrangthai = 200 })))
                                .Events(e => e.Change("Change_MaNhom"))
                        )
                    </div>
                </div>
            </div>
        </text>);
    })
                                                                                            .Pageable(pageable => pageable.PageSizes(new int[] { 5,10,20, 50, 100,200,500,1000 }).ButtonCount(gridPageSize))
                                                                                            .Sortable()
                                                                                            .Scrollable()
                                                                                            .Selectable()
                                                                                            .Filterable()
                                                                                            .Navigatable()
                                                                                            .Resizable(resize => resize.Columns(true))
                                                                                            .DataSource(dataSource => dataSource
                                                                                            .Ajax()
                                                                                            .ServerOperation(false)
                                                                                            .Model(model => model.Id(p => p.Key))
                                                                                             .Read(read => read.Action("Read", "Resource"))
                                                                                            .PageSize(gridPageSize)
                                                                                            )
                                                                                            .Events(e => e.DataBound("grid_DataBound"))
    )
</div>

@*Bound*@
<script>
    var __IdCode = 0;
    function grid_DataBound() {
        var idCode = __IdCode;
        var grid = $("#grid").data("kendoGrid");
        var data = grid.dataSource.data();
        var totalNumber = data.length;
        var index = 0;
        var row;
        for (var i = 0; i < totalNumber; i++) {
            row = data[i];
            if (row.Key == idCode) {
                index = i + 1;
                var model = grid.dataSource.get(idCode);
                var row1 = $("#grid").find("tbody>tr[data-uid=" + model.uid + "]");
                grid.select(row1);
                break;
            }
        }
        var pageSize = grid.dataSource._pageSize;//Số bản ghi trên 1 trang
        var cpage = this.dataSource.page();//Trang hiện tại
        var page = Math.floor(index / pageSize);
        if ((index % pageSize) != 0) {
            //Công thêm trang nếu số dư # 0
            page = page + 1;
        }

        if (cpage != page && page != 0) {
            grid.dataSource.page(page);
        }
        //Chọn ban ghi đầu tiên,xóa  khi IdCode=""
        if (idCode == "") {
            var tpage = Math.floor(totalNumber / pageSize);//Tổng số trang của grid
            if ((totalNumber % pageSize) != 0) {
                tpage = Math.floor(totalNumber / pageSize) + 1;
            }
            //kiểm tra nếu tổng số trang < trang hiện tại thì lùi lại 1 trang .Ngược lại chon bản ghi đầu tiên trang đó
            if (tpage < cpage && tpage != 0) {
                grid.dataSource.page(tpage);
            }
            //Chon row 0
            row = grid.tbody.find(">tr:not(.k-grouping-row)").eq(0);
            grid.select(row);
        }

        __IdCode = 0;

        //Autosroll grid
        if (index != 0) {
            ////Autoscroll
            var scrollContentOffset = this.element.find("tbody").offset().top;
            var selectContentOffset = this.select().offset().top;
            var distance = selectContentOffset - scrollContentOffset;

            //    animate our scroll
            this.element.find(".k-grid-content").animate({
                scrollTop: distance
            }, 400);
        }
        //Autosroll grid
    }

    function ActiveRow(idCode) {
        __IdCode = idCode;
    }

    function voidRefresh() {
        LoadDataFind();
    }

    function VoidSearch() {

    }
    function Change_MaNhom() {
        LoadDataFind();
    }
    function txtSearch_textChanged() {
        LoadDataFind();
    }

    function LoadDataFind() {
        $("#grid").data("kendoGrid").dataSource.read({ tukhoa: $("#txtSearch").val(), filename: $("#CbMa_nhom").data("kendoDropDownList").value() });
    }


</script>


@*Grid height*@
<script type="text/javascript">
    $(document).ready(function () {
        //Set Grid height
        GridHeight("grid");
    });
    Toolbar_Click();
</script>

@*div Main*@
<div>
    @(Html.Kendo().Window()
    .Name("WidgetConfigWindow")
     .Iframe(true)
     .Events(ev => ev.Open(@"function(f){
        if(window.loaded){
            this.refresh();
        }
        window.loaded = true;
    }"))
    .Animation(true)
    .Resizable()
    .Draggable()
    .Width(890)
    .Height(510)
    .Actions(actions => actions.Pin().Minimize().Maximize().Close())
    .HtmlAttributes(new { style = "marign:0;padding:0;overflow:hidden" })
    .Visible(false)
    .Modal(true)
    )
</div>

@*CED Main*@
<script>

    function GetId() {
        var grid = $("#grid").data("kendoGrid");
        var Key = "";
        if (grid.select().length > 0) {
            var dataItem = grid.dataItem(grid.select());
            if (dataItem != null) {
                Key = dataItem.Key;
            }
        }
        return Key;
    }

    function Edit() {
        var grid = $("#grid").data("kendoGrid");
        var dataItem = grid.dataItem(grid.select());
        var windowWidget = $("#WidgetConfigWindow").data("kendoWindow");
        if (dataItem != null) {
            windowWidget.refresh({
                url: '@Url.Action("Edit", "Resource")?key=' + GetId() + '& filename=' +$("#CbMa_nhom").data("kendoDropDownList").value() 
            });
            windowWidget.center();
            windowWidget.open();
        }
    }


</script>